# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m0dwoTAa843WsddgpTYKPD1cFBKFRSG0
"""

import csv
from faker import Faker
import random

# Initialize Faker and set the seed for reproducibility
fake = Faker()
Faker.seed(123)

# Generate data for 1000 books
books_data = []
for i in range(1, 1001):
    title = fake.sentence(nb_words=5)
    author = fake.name()
    isbn = fake.isbn13()
    published_date = fake.date_of_birth(tzinfo=None, minimum_age=10, maximum_age=100)
    genre = fake.word()
    shelf_location = fake.word().upper()
    current_status = random.choice(['Available', 'Borrowed'])

    books_data.append([i, title, author, isbn, published_date, genre, shelf_location, current_status])

# Save data to a CSV file
with open('books_data.csv', 'w', newline='') as csvfile:
    csvwriter = csv.writer(csvfile)
    csvwriter.writerow(['BookID', 'Title', 'Author', 'ISBN', 'PublishedDate', 'Genre', 'ShelfLocation', 'CurrentStatus'])
    csvwriter.writerows(books_data)

import csv
from faker import Faker
import random
import datetime

# Initialize Faker and set the seed for reproducibility
fake = Faker()
Faker.seed(123)

# Generate data for 1000 borrowers
borrowers_data = []
for i in range(1, 1001):
    first_name = fake.first_name()
    last_name = fake.last_name()
    email = fake.email()
    date_of_birth = fake.date_of_birth(tzinfo=None, minimum_age=18, maximum_age=100)
    membership_date = fake.date_between_dates(date_of_birth, datetime.date.today())

    borrowers_data.append([i, first_name, last_name, email, date_of_birth, membership_date])

# Save data to a CSV file
with open('borrowers_data.csv', 'w', newline='') as csvfile:
    csvwriter = csv.writer(csvfile)
    csvwriter.writerow(['BorrowerID', 'FirstName', 'LastName', 'Email', 'DateOfBirth', 'MembershipDate'])
    csvwriter.writerows(borrowers_data)